# Generated by Django 5.2.4 on 2025-07-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_information_product_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='product.product'),
        ),
    ]
