# Generated by Django 5.2.4 on 2025-07-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdiscount',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderdiscount'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='code',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
