# Generated by Django 5.2.4 on 2025-07-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_orderdiscount_name_order_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_code', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.DeleteModel(
            name='OrderDiscount',
        ),
    ]
